export const initialMealBuilderOptions = [
  // BASES
  {
    name: 'Organic Brown Rice',
    description: 'Complex carbohydrate base with fiber for long-lasting energy.',
    category: 'base',
    price: 60,
    calories: 215,
    protein: 5,
    carbs: 45,
    fats: 2,
    dietaryPreference: 'vegan',
    allergens: [],
    tags: ['Slow Digesting', 'Complex Carb'],
    isAvailable: true,
  },
  {
    name: 'Tri-Color Quinoa',
    description: 'Complete plant protein base packed with essential amino acids.',
    category: 'base',
    price: 80,
    calories: 220,
    protein: 8,
    carbs: 39,
    fats: 3.5,
    dietaryPreference: 'vegan',
    allergens: [],
    tags: ['Superfood', 'High Fiber'],
    isAvailable: true,
  },
  {
    name: 'Cauliflower Rice',
    description: 'Ultra-low-carb grain-free base ideal for fat loss & keto diets.',
    category: 'base',
    price: 70,
    calories: 45,
    protein: 3,
    carbs: 8,
    fats: 0.5,
    dietaryPreference: 'vegan',
    allergens: [],
    tags: ['Keto', 'Low Calorie'],
    isAvailable: true,
  },

  // PROTEINS
  {
    name: 'Charcoal Tandoori Chicken Breast',
    description: 'Lean skinless chicken breast marinated in active spices and grilled over coals.',
    category: 'protein',
    price: 160,
    calories: 240,
    protein: 42,
    carbs: 2,
    fats: 5,
    dietaryPreference: 'nonVegetarian',
    allergens: [],
    tags: ['Lean Muscle', 'High Protein'],
    isAvailable: true,
  },
  {
    name: 'Herb-Grilled Cottage Cheese (Paneer)',
    description: 'Fresh artisanal cottage cheese seared with oregano and crushed black pepper.',
    category: 'protein',
    price: 140,
    calories: 260,
    protein: 24,
    carbs: 4,
    fats: 16,
    dietaryPreference: 'vegetarian',
    allergens: ['dairy'],
    tags: ['Rich Calcium', 'Vegetarian Fuel'],
    isAvailable: true,
  },
  {
    name: 'Baked Crispy Organic Tofu',
    description: 'Non-GMO soybean curd baked till golden crisped.',
    category: 'protein',
    price: 130,
    calories: 180,
    protein: 20,
    carbs: 4,
    fats: 9,
    dietaryPreference: 'vegan',
    allergens: ['soy'],
    tags: ['100% Plant-Based', 'Zero Cholesterol'],
    isAvailable: true,
  },

  // CARBS
  {
    name: 'Rosemary Roasted Sweet Potato Wedges',
    description: 'Nutrient-rich sweet potato wedges roasted in extra virgin olive oil.',
    category: 'carb',
    price: 50,
    calories: 160,
    protein: 2,
    carbs: 37,
    fats: 1,
    dietaryPreference: 'vegan',
    allergens: [],
    tags: ['Glycogen Replenish', 'Vitamin A'],
    isAvailable: true,
  },
  {
    name: 'Steamed Sweet Corn & Black Beans',
    description: 'Fiber-packed carbohydrate combo for steady workouts.',
    category: 'carb',
    price: 45,
    calories: 140,
    protein: 6,
    carbs: 28,
    fats: 1.5,
    dietaryPreference: 'vegan',
    allergens: [],
    tags: ['High Fiber', 'Post-Workout'],
    isAvailable: true,
  },

  // VEGETABLES
  {
    name: 'Steamed Broccoli & Green Beans',
    description: 'Crisp green micronutrient medley.',
    category: 'vegetables',
    price: 40,
    calories: 35,
    protein: 3,
    carbs: 6,
    fats: 0.5,
    dietaryPreference: 'vegan',
    allergens: [],
    tags: ['Antioxidant', 'Micronutrients'],
    isAvailable: true,
  },
  {
    name: 'Grilled Zucchini & Bell Peppers',
    description: 'Flame-grilled colorful vegetables.',
    category: 'vegetables',
    price: 45,
    calories: 40,
    protein: 2,
    carbs: 7,
    fats: 0.5,
    dietaryPreference: 'vegan',
    allergens: [],
    tags: ['Low Calorie', 'Vitamin C'],
    isAvailable: true,
  },

  // SAUCES
  {
    name: 'House Lemon-Herb Vinaigrette',
    description: 'Cold-pressed olive oil, fresh lemon juice, garlic, and fresh herbs.',
    category: 'sauce',
    price: 25,
    calories: 60,
    protein: 0,
    carbs: 2,
    fats: 6,
    dietaryPreference: 'vegan',
    allergens: [],
    tags: ['Clean Dressing', 'Healthy Fats'],
    isAvailable: true,
  },
  {
    name: 'Tandoori Mint Yogurt Dressing',
    description: 'Greek yogurt whipped with fresh mint leaves and roasted cumin.',
    category: 'sauce',
    price: 30,
    calories: 45,
    protein: 3,
    carbs: 3,
    fats: 2,
    dietaryPreference: 'vegetarian',
    allergens: ['dairy'],
    tags: ['Probiotic', 'Low Fat'],
    isAvailable: true,
  },

  // EXTRAS
  {
    name: 'Hass Avocado Slices',
    description: 'Rich creamy slices of nutrient-dense avocado.',
    category: 'extras',
    price: 60,
    calories: 120,
    protein: 1.5,
    carbs: 6,
    fats: 11,
    dietaryPreference: 'vegan',
    allergens: [],
    tags: ['Monounsaturated Fats', 'Keto'],
    isAvailable: true,
  },
  {
    name: 'Toasted Pumpkin & Flaxseed Mix',
    description: 'Crunchy seed blend loaded with Omega-3 and magnesium.',
    category: 'extras',
    price: 35,
    calories: 80,
    protein: 4,
    carbs: 3,
    fats: 6,
    dietaryPreference: 'vegan',
    allergens: [],
    tags: ['Omega-3', 'Crunchy Crunch'],
    isAvailable: true,
  },
];
