export const initialMenuItems = [
  {
    name: 'Grilled Charcoal Chicken Bowl',
    slug: 'grilled-charcoal-chicken-bowl',
    description:
      'Smokey tandoori-marinated chicken breast served with organic brown rice, steamed broccoli, and house mint yogurt.',
    price: 349,
    image:
      'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    category: 'highProtein',
    dietaryPreference: 'nonVegetarian',
    fitnessGoals: ['muscleGain', 'performance'],
    macros: { calories: 580, protein: 52, carbs: 48, fats: 14 },
    ingredients: [
      'Chicken Breast',
      'Brown Rice',
      'Broccoli',
      'Mint Yogurt',
      'Tandoori Spices',
    ],
    allergens: ['dairy'],
    fuelScore: 94,
    preparationTime: 20,
    isAvailable: true,
    tags: ['Best Seller', 'High Protein', 'Post-Workout'],
  },
  {
    name: 'Steak & Sweet Potato Power Plate',
    slug: 'steak-sweet-potato-power-plate',
    description:
      'Seared tenderloin steak strips served with roasted rosemary sweet potato wedges and grilled asparagus.',
    price: 449,
    image:
      'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    category: 'muscleGain',
    dietaryPreference: 'nonVegetarian',
    fitnessGoals: ['muscleGain', 'performance'],
    macros: { calories: 650, protein: 58, carbs: 52, fats: 18 },
    ingredients: [
      'Tenderloin Steak',
      'Sweet Potato',
      'Asparagus',
      'Rosemary',
      'Olive Oil',
    ],
    allergens: [],
    fuelScore: 92,
    preparationTime: 25,
    isAvailable: true,
    tags: ['Heavy Muscle Fuel', 'Chef Special'],
  },
  {
    name: 'Paneer Power Protein Salad',
    slug: 'paneer-power-protein-salad',
    description:
      'Herb-grilled cottage cheese cubes over crisp baby spinach, quinoa, cherry tomatoes, and lemon vinaigrette.',
    price: 299,
    image:
      'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    category: 'fatLoss',
    dietaryPreference: 'vegetarian',
    fitnessGoals: ['fatLoss', 'eatClean'],
    macros: { calories: 410, protein: 34, carbs: 24, fats: 18 },
    ingredients: [
      'Low-Fat Cottage Cheese',
      'Quinoa',
      'Baby Spinach',
      'Cherry Tomatoes',
      'Lemon Dressing',
    ],
    allergens: ['dairy'],
    fuelScore: 89,
    preparationTime: 15,
    isAvailable: true,
    tags: ['Keto Friendly', 'Vegetarian Star'],
  },
  {
    name: 'Vegan Macro Power Bowl',
    slug: 'vegan-macro-power-bowl',
    description:
      'Crispy baked tofu, edamame, tri-color quinoa, roasted beets, and house tahini garlic dressing.',
    price: 329,
    image:
      'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    category: 'performance',
    dietaryPreference: 'vegan',
    fitnessGoals: ['eatClean', 'performance'],
    macros: { calories: 460, protein: 31, carbs: 54, fats: 12 },
    ingredients: [
      'Organic Tofu',
      'Edamame',
      'Tri-Color Quinoa',
      'Beetroot',
      'Tahini Sauce',
    ],
    allergens: ['soy', 'sesame'],
    fuelScore: 95,
    preparationTime: 18,
    isAvailable: true,
    tags: ['100% Plant Power', 'Clean Fuel'],
  },
  {
    name: 'Egg & Avocado Fuel Toast Bowl',
    slug: 'egg-avocado-fuel-toast-bowl',
    description:
      'Poached free-range farm eggs over mashed avocado, chili flakes, and toasted sourdough multiseed crust.',
    price: 279,
    image:
      'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80',
    category: 'preWorkout',
    dietaryPreference: 'eggitarian',
    fitnessGoals: ['performance', 'eatClean'],
    macros: { calories: 430, protein: 26, carbs: 36, fats: 20 },
    ingredients: [
      'Free-Range Eggs',
      'Hass Avocado',
      'Multiseed Sourdough',
      'Chili Flakes',
    ],
    allergens: ['egg', 'gluten'],
    fuelScore: 90,
    preparationTime: 12,
    isAvailable: true,
    tags: ['Quick Energy', 'Eggitarian Special'],
  },
  {
    name: 'Whey Protein Electrolyte Smoothie',
    slug: 'whey-protein-electrolyte-smoothie',
    description:
      'Isolate whey protein blended with frozen blueberries, coconut water, banana, and chia seeds.',
    price: 199,
    image:
      'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80',
    category: 'drinks',
    dietaryPreference: 'vegetarian',
    fitnessGoals: ['muscleGain', 'performance'],
    macros: { calories: 280, protein: 32, carbs: 30, fats: 3 },
    ingredients: [
      'Whey Isolate',
      'Blueberries',
      'Banana',
      'Coconut Water',
      'Chia Seeds',
    ],
    allergens: ['dairy'],
    fuelScore: 96,
    preparationTime: 5,
    isAvailable: true,
    tags: ['Post-Workout Shake', 'Fast Recovery'],
  },
];
